### ISSUE TITLE
Make it easier to add documents to pages

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_core#253]
Mentioned at LGD Camp, and also picked up by @benhillsjones in Dumfries

> As a content designer
> I need to insert a document at a specific point on a page and give it custom link text

@dedavidson has been working on a fix for this

**Comment by dedavidson** [comment]
The fix for this is to add config to `modules/localgov_media/config/optional/linkit.linkit_profile.default.yml` the `localgov_core` project. ( https://github.com/localgovdrupal/localgov_core/blob/2.x/modules/localgov_media/config/optional/linkit.linkit_profile.default.yml )

 It requires adding the following config to the `matchers` section:
```
  <a uuid>:
    id: 'entity:media'
    uuid: <a uuid>
    settings:
      metadata: ''
      bundles:
        document: document
      group_by_bundle: false
      substitution_type: media
      limit: 100
    weight: 0
```
